created post req to get all messages for each chat
Moonshot-io/vibes pull request #118
Opened 2022-08-20 21:00 UTC by rysmith504

2022-08-20 21:16 UTC, BethanyAJones requested changes
If you want your component to have dark mode capabilities, please bring over my implementations in your new file. I'm not redoing it.

2022-08-20 22:12 UTC, dow2 approved these changes
please transfer bethanys style changes to your updates

2022-08-21 18:54 UTC, BethanyAJones approved these changes

2022-08-21 18:57 UTC, merged

2022-08-21 18:58 UTC, bchau1242 approved these changes